### ISSUE TITLE
Trados Studio -memoQ - wordfast RemotTM plugins

### ISSUE THREAD

**Issue by drkhateeb** [rmraya/RemoteTM#1]
Hello dear dev
kindly create plugins for these CAT tools to utilize remotTM

memoQ :
Documentations:
https://docs.memoq.com/current/api-docs/wsapi/api/tmservice/MemoQServices.html

https://docs.memoq.com/current/sdk-docs/
https://docs.memoq.com/current/sdk-docs/memoQ-TB-SDK-2.4.1.zip

https://docs.memoq.com/current/sdk-docs/memoQ-TM-SDK-2.4.1.zip
create TM/TB plugin for sharing and collaboration team
GIThub repository
wordfastanywhere API to store and share TM/TB
https://www.wordfast.net/wiki/Wordfast_Anywhere_TMs_and_glossaries_API
-----
Trados:
https://github.com/RWS/Sdl-Community

https://www.nuget.org/packages/Trados.Community.Toolkit.LanguagePlatform

Trados Translation Memory Api
Terminology Provider Api
Similar Plugins:
https://github.com/RWS/Sdl-Community/tree/master/TAUS%20Data%20Search
https://github.com/RWS/Sdl-Community/tree/master/IATETerminologyProvider

the requested plugin will connect Studio to RemotTM TM and TB via API

**Comment by rmraya** [comment]
Contact rmraya@maxprograms.com and request a quote if you are willing to sponsor the development of the plugins.
